### ISSUE TITLE
Error while creating a bucket

### ISSUE THREAD

**Issue by nperraud** [SwissDataScienceCenter/renga-projects#24]
Step to reproduce the error
```
mkvirtualenv renga -p `which python3`
pip install renga
renga login --client-id renga-client https://testing.datascience.ch
mkdir project2
cd project2
renga io buckets create -b swift testing_bucket
```

Result:
```
/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/renga/api/client.py:83: UserWarning: Using insecure trasnport protocol, use HTTPS
  warnings.warn('Using insecure trasnport protocol, use HTTPS')
Traceback (most recent call last):
  File "/Users/nati/.virtualenvs/renga/bin/renga", line 11, in <module>
    sys.exit(cli())
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/renga/cli/_config.py", line 91, in new_func
    result = ctx.invoke(f, config, *args, **kwargs)
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/renga/cli/io.py", line 56, in create
    client = from_config(config, endpoint=endpoint)
  File "/Users/nati/.virtualenvs/renga/lib/python3.6/site-packages/renga/cli/_client.py", line 48, in from_config
    'endpoints'][endpoint]['vertex_id']
KeyError: 'http://localhost'
```

The config.yml file reads:
```
cat .renga/config.yml
core:
  autosync: true
  generated: '2017-11-17T09:52:25.405266'
  name: project2
endpoints:
  https://testing.datascience.ch:
    vertex_id: '12480'
```

**Comment by leafty** [comment]
This is a client misconfiguration.
